config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :tutors do
    resources :comments
  end
  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :tutor
end

app/models/tutor.rb
class Tutor < ActiveRecord::Base
	has_many :comments, dependent: :destroy
  	validates :title, presence: true,
                    	length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	# http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
	
	def create
	    @tutor = Tutor.find(params[:tutor_id])
	    @comment = @tutor.comments.create(comment_params)
	    redirect_to tutor_path(@tutor)
	 end

	def destroy
		@tutor = Tutor.find(params[:tutor_id])
		@comment = @tutor.comments.find(params[:id])
		@comment.destroy
		redirect_to tutor_path(@tutor)
	end

	private
		def comment_params
		  params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
	
	# http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
	
	def index
    	@tutors = Tutor.all
  	end

	def show
    	@tutor = Tutor.find(params[:id])
  	end

	def new
		@tutor = Tutor.new
	end
	 
	def edit
  		@tutor = Tutor.find(params[:id])
	end


	def create
	 	@tutor = Tutor.new(tutor_params)
	 
	  if @tutor.save
	    redirect_to @tutor
	  else
	    render 'new'
	  end
	end

	def update
  		@tutor = Tutor.find(params[:id])
 
  		if @tutor.update(tutor_params)
    	redirect_to @tutor
  		else
    	render 'edit'
  		end
  	end

  	def destroy
		@tutor = Tutor.find(params[:id])
		@tutor.destroy
	 
		redirect_to tutors_path
	end

	private
	  def tutor_params
	    params.require(:tutor).permit(:title, :text)
	  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.tutor, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@tutor, @tutor.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for :student, url: students_path do |s| %>
 
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@student.errors.count, "error") %> prohibited
        this student from being saved:
      </h2>
      <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= s.label :name %><br>
    <%= s.text_field :name %>
  </p>
 
  <p>
    <%= s.label :year %><br>
    <%= s.text_field :year %>
  </p>

  <p>
    <%= s.label :courses %><br>
    <%= s.text_area :courses %>
  </p>
 
  <p>
    <%= s.submit %>
  </p>
 
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<%-# This should only be available to the owners-%>

<h1>Listing students</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Year</th>
    <th>Courses</th>
    <th colspan="2"></th>
  </tr>
 
  <% @students.each do |student| %>
    <tr>
      <td><%= student.name %></td>
      <td><%= student.year %></td>
      <td><%= student.courses %></td>
      <td><%= link_to 'Show', student_path(student) %></td>
      <td><%= link_to 'Edit', edit_student_path(student) %></td>

    </tr>
  <% end %>
</table>

<%= link_to 'Back', welcome_index_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>
 
<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>
 
<p>
  <strong>Year:</strong>
  <%= @student.year %>
</p>

<p>
  <strong>Courses:</strong>
  <%= @student.courses %>
</p>

<%= link_to 'Back', students_path %> |
<%= link_to 'Edit', edit_student_path(@student) %>

app/views/tutors/_form.html.erb
<%= form_for @tutor do |f| %>
 
  <% if @tutor.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@tutor.errors.count, "error") %> prohibited
        this tutor from being saved:
      </h2>
      <ul>
        <% @tutor.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/tutors/edit.html.erb
<h1>Editing tutor</h1>

<%= render 'form' %>
 
<%= link_to 'Back', tutors_path %>

app/views/tutors/index.html.erb
<h1>Listing Tutors</h1>
<%= link_to 'New tutor', new_tutor_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @tutors.each do |tutor| %>
    <tr>
      <td><%= tutor.title %></td>
      <td><%= tutor.text %></td>
      <td><%= link_to 'Show', tutor_path(tutor) %></td>
      <td><%= link_to 'Edit', edit_tutor_path(tutor) %></td>
      <td><%= link_to 'Destroy', tutor_path(tutor),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/tutors/new.html.erb
<h1>New tutor</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', tutors_path %>

app/views/tutors/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @tutor.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @tutor.text %>
</p>

<h2>Comments</h2>
<%= render @tutor.comments %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Back', tutors_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'tutors' %>
<%= link_to 'New tutor', new_tutor_path %>